name: 📄 Documentation
description: Found an issue in the documentation? You can use this one!
title: '[DOCS] Description'
labels: ['docs']
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Description of the question or issue, also include what you tried and what didn't work
    validations:
      required: true
